"""auto-vote-table

Revision ID: 9dd8f2890eb3
Revises: 1a3ef7d02da3
Create Date: 2024-02-13 12:17:11.530355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd8f2890eb3'
down_revision: Union[str, None] = '1a3ef7d02da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # used '''alembic revision --autogenerate -m "aut-vote-table" '''
    # ALEMBIC CREATES votes with post_id and user_id as primary keys which is a composite key
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id') # create composite key
    )
    # ### end Alembic --autogenerate commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
